### ISSUE TITLE
source tarballs should not include binaries

### ISSUE THREAD

**Issue by alexmyczko** [smanders/geotranz#1]
can you remove the following binaries?

```
SpreadsheetTester/win*
SpreadsheetTester/linux*/MSPCCS_SpreadsheetTester
CCS/linux*/*.so
CCS/linux*/*.so*
GEOTRANS3/linux*/libjnimsp_ccs.so
```

**Comment by smanders** [comment]
short answer: no, I won't remove them
preferred solution: fork this repo and remove them yourself

more detailed explanation:
I don't control the geotrans project in any way. The master branch of this repo is very simply a commit for every version of a tgz from an external entity (which is the entity that controls the geotrans project). See the list of commits: https://github.com/smanders/geotranz/commits/master and you will see a commit for each version.

I don't intend to modify what *they* decided to include in their tgz in the master branch of this repo. The master branch will always match the "upstream" source. This allows me to `git checkout [tag]` and match the contents of *their* tgz.

Any modifications I deem necessary are done in a branch off of the tagged version commit -- for example the `xp2.4.2` branch has commits on top of the `v2.4.2` tag/commit https://github.com/smanders/geotranz/compare/v2.4.2...xp2.4.2

I use this diff to create a patch file that I apply on top of *their* tgz that *they* give to the world.

I agree with you that it would be a better tgz if they didn't include binaries. But the place to request this is not here... you should be making this request to NGA http://earth-info.nga.mil/GandG/geotrans/ who controls geotrans
